// <auto-generated />
using System;
using Infrastructure.Context.Security;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations.SecurityMigrations
{
    [DbContext(typeof(SecurityContext))]
    [Migration("20220628161917_SecurityCreate")]
    partial class SecurityCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Infrastructure.Entities.Security.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CodeCoverPassword")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateOnAudit")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdPerson")
                        .HasColumnType("int");

                    b.Property<int>("IdTypeSubscription")
                        .HasColumnType("int");

                    b.Property<int>("IdTypeUser")
                        .HasColumnType("int");

                    b.Property<int?>("IdUserModifyAudit")
                        .HasColumnType("int");

                    b.Property<int>("IdUserRegisterAudit")
                        .HasColumnType("int");

                    b.Property<string>("IpPublicAudit")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsRecoverPassword")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("KeyUnique")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LatitudeAudit")
                        .HasColumnType("longtext");

                    b.Property<string>("LongitudeAudit")
                        .HasColumnType("longtext");

                    b.Property<string>("MacAddressAudit")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifyOnAudit")
                        .HasColumnType("datetime");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("StateUser")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.ToTable("user", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
