// <auto-generated />
using System;
using Infrastructure.Context.Security;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations.Seguridad
{
    [DbContext(typeof(SecurityContext))]
    [Migration("20220704144836_PersonaUsuario")]
    partial class PersonaUsuario
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Infrastructure.Entities.Security.PersonEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ApellidosCompletos")
                        .HasColumnType("longtext");

                    b.Property<string>("Cedula")
                        .HasColumnType("longtext");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateOnAudit")
                        .HasColumnType("datetime");

                    b.Property<string>("Direccion")
                        .HasColumnType("longtext");

                    b.Property<string>("DireccionSecundario")
                        .HasColumnType("longtext");

                    b.Property<byte>("Estado")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime");

                    b.Property<string>("FotoPerfil")
                        .HasColumnType("longtext");

                    b.Property<int>("IdGenero")
                        .HasColumnType("int");

                    b.Property<int?>("IdNacionalidad")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoIdentificacion")
                        .HasColumnType("int");

                    b.Property<int?>("IdUserModifyAudit")
                        .HasColumnType("int");

                    b.Property<int>("IdUserRegisterAudit")
                        .HasColumnType("int");

                    b.Property<string>("IpPublicAudit")
                        .HasColumnType("longtext");

                    b.Property<string>("LatitudeAudit")
                        .HasColumnType("longtext");

                    b.Property<string>("LongitudeAudit")
                        .HasColumnType("longtext");

                    b.Property<string>("MacAddressAudit")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifyOnAudit")
                        .HasColumnType("datetime");

                    b.Property<string>("NombresCompletos")
                        .HasColumnType("longtext");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("longtext");

                    b.Property<int?>("Telefono")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("persona", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.Security.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ClaveUnica")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoRecuperacion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateOnAudit")
                        .HasColumnType("datetime");

                    b.Property<int>("IdPersona")
                        .HasColumnType("int");

                    b.Property<int>("IdSuscripcion")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoUsuario")
                        .HasColumnType("int");

                    b.Property<int?>("IdUserModifyAudit")
                        .HasColumnType("int");

                    b.Property<int>("IdUserRegisterAudit")
                        .HasColumnType("int");

                    b.Property<string>("IpPublicAudit")
                        .HasColumnType("longtext");

                    b.Property<string>("LatitudeAudit")
                        .HasColumnType("longtext");

                    b.Property<string>("LongitudeAudit")
                        .HasColumnType("longtext");

                    b.Property<string>("MacAddressAudit")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifyOnAudit")
                        .HasColumnType("datetime");

                    b.Property<bool>("RecuperarContraseña")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte>("StateUser")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.ToTable("usuario", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
