// <auto-generated />
using System;
using Infrastructure.Context.Security;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations.Seguridad
{
    [DbContext(typeof(SecurityContext))]
    [Migration("20220719201127_PersonaCreate")]
    partial class PersonaCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Infrastructure.Entities.Security.AdnPagoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CodigoTelefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateOnAudit")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Cuenta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("Estado")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("IdBanco")
                        .HasColumnType("int");

                    b.Property<Guid>("IdPersona")
                        .HasColumnType("char(36)");

                    b.Property<string>("IdUserModifyAudit")
                        .HasColumnType("longtext");

                    b.Property<string>("IdUserRegisterAudit")
                        .HasColumnType("longtext");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IpPublicAudit")
                        .HasColumnType("longtext");

                    b.Property<string>("LatitudeAudit")
                        .HasColumnType("longtext");

                    b.Property<string>("LongitudeAudit")
                        .HasColumnType("longtext");

                    b.Property<string>("MacAddressAudit")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifyOnAudit")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TipoCuenta")
                        .HasColumnType("int");

                    b.Property<string>("Titular")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("adnpago", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.Security.AdnTiendaCategoriaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdAdnTienda")
                        .HasColumnType("int");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tiendacategoria", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.Security.AdnTiendaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Ciudad")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateOnAudit")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DescripcionTienda")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("Estado")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("FotoTienda")
                        .HasColumnType("longtext");

                    b.Property<Guid>("IdPersona")
                        .HasColumnType("char(36)");

                    b.Property<string>("IdUserModifyAudit")
                        .HasColumnType("longtext");

                    b.Property<string>("IdUserRegisterAudit")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("InicioActividades")
                        .HasColumnType("datetime");

                    b.Property<string>("IpPublicAudit")
                        .HasColumnType("longtext");

                    b.Property<string>("LatitudeAudit")
                        .HasColumnType("longtext");

                    b.Property<string>("LongitudeAudit")
                        .HasColumnType("longtext");

                    b.Property<string>("MacAddressAudit")
                        .HasColumnType("longtext");

                    b.Property<bool>("MasLocales")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ModifyOnAudit")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Pais")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Tienda")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("adntienda", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.Security.PersonEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ApellidosCompletos")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoTelefono")
                        .HasColumnType("longtext");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateOnAudit")
                        .HasColumnType("datetime");

                    b.Property<string>("DescripcionPersona")
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .HasColumnType("longtext");

                    b.Property<string>("DireccionSecundario")
                        .HasColumnType("longtext");

                    b.Property<byte>("Estado")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime?>("FechaNacimiento")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("FotoPerfil")
                        .HasColumnType("longtext");

                    b.Property<int?>("IdGenero")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("IdPais")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoIdentificacion")
                        .HasColumnType("int");

                    b.Property<string>("IdUserModifyAudit")
                        .HasColumnType("longtext");

                    b.Property<string>("IdUserRegisterAudit")
                        .HasColumnType("longtext");

                    b.Property<string>("Identificacion")
                        .HasColumnType("longtext");

                    b.Property<string>("IpPublicAudit")
                        .HasColumnType("longtext");

                    b.Property<string>("LatitudeAudit")
                        .HasColumnType("longtext");

                    b.Property<string>("LongitudeAudit")
                        .HasColumnType("longtext");

                    b.Property<string>("MacAddressAudit")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifyOnAudit")
                        .HasColumnType("datetime");

                    b.Property<string>("NombresCompletos")
                        .HasColumnType("longtext");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("persona", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.Security.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ClaveUnica")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoRecuperacion")
                        .HasColumnType("longtext");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateOnAudit")
                        .HasColumnType("datetime");

                    b.Property<int>("IdPersona")
                        .HasColumnType("int");

                    b.Property<int?>("IdSuscripcion")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoUsuario")
                        .HasColumnType("int");

                    b.Property<string>("IdUserModifyAudit")
                        .HasColumnType("longtext");

                    b.Property<string>("IdUserRegisterAudit")
                        .HasColumnType("longtext");

                    b.Property<string>("IpPublicAudit")
                        .HasColumnType("longtext");

                    b.Property<string>("LatitudeAudit")
                        .HasColumnType("longtext");

                    b.Property<string>("LongitudeAudit")
                        .HasColumnType("longtext");

                    b.Property<string>("MacAddressAudit")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifyOnAudit")
                        .HasColumnType("datetime");

                    b.Property<bool?>("RecuperarContraseña")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte>("StateUser")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.ToTable("usuario", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
